### ISSUE TITLE
Misundersting manual mode

### ISSUE THREAD

**Issue by welcoMattic** [ihrwein/ansible-syslog-ng#5]
Hi!

Thanks for your role, it's really nice!

However, I'm misunderting the manual mode. Where should I store my own `syslog-ng.conf` file to be copied automatically?

Thanks for your answer.

**Comment by ihrwein** [comment]
For example, If your `syslog_ng_config_version` is `3.5`, you have to edit `templates/manual/syslog-ng/3.5/syslog-ng.j2`.

**Comment by welcoMattic** [comment]
But when I install the role, can I set the path of my own syslog-ng.j2 file?
If not, all other developers of my team have to modify this file in there own installation too, right?

**Comment by ihrwein** [comment]
Sorry for the late answer. You are right. Unfortunately, I haven't used Ansible for a while (and didn't track its development) so I don't know what would be the current best solution.

**Comment by welcoMattic** [comment]
No problem! I'm working every day with Ansible since few weeks.
May I'll fork your playbook and find a (the?) best way to make customizable the template for a team.

Thanks for your work!

**Comment by ihrwein** [comment]
As you wish! I'm open to any help :)

**Comment by welcoMattic** [comment]
Thank you!
